# Generated by Django 3.2 on 2022-06-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_vacation_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='time_create',
            field=models.DateField(auto_now_add=True),
        ),
    ]
