# Generated by Django 3.2 on 2022-04-08 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_department_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='on_boarding_day',
            field=models.DateField(default=datetime.date),
        ),
    ]
