# Generated by Django 3.2 on 2022-04-08 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_employee_on_boarding_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='on_boarding_day',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
