name: Python-package

on: [push]

jobs:
  Coverage_job:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          cd src
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Run coverage
        run: |
          python management/manage.py migrate
          coverage run --source='management' management/manage.py test management
          coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}