name: Linter
on:
  push:
    paths:
      - '*.py'

jobs:
  Linter_job:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7.4
          architecture: x64
      - name: Checkout PyTorch
        uses: actions/checkout@master
      - name: Install dependencies
        run: |
            cd src
            python -m pip install -U pip
            pip install -r requirements.txt
            cd management
      - name: Run flake8
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: 'Linter_job'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}